/** Refresh the vendored snapshot from the canonical Studio skill; not a publish-time dependency. */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';

const source = process.argv[2];
if (!source) throw new Error('Pass the canonical make-custom-video skill directory');
const core = readFileSync(join(source, 'SKILL.md'), 'utf8').replace('name: make-custom-video\n', 'name: make-custom-video\nslug: make-custom-video\n');
const integration = readFileSync(join(source, 'integration.md'), 'utf8');
const assembly = readFileSync(join(source, 'scripts/assemble.py'), 'utf8');
const content = `${core}\n---\n\n${integration}\n\n## Portable assembly helper\n\nSave the following as assemble.py in your temporary production directory. Run it with Python, a saved JSON plan and an output MP4 path. It makes no provider calls and does not mark the result visually approved.\n\n\`\`\`python\n${assembly}\n\`\`\`\n`;
const hash = createHash('sha256').update(content).digest('hex');
writeFileSync('src/skills/custom-video-skill.ts', `// Generated by scripts/sync-custom-video-skill.ts. Canonical content SHA256: ${hash}\nexport const CUSTOM_VIDEO_SKILL_CONTENT = ${JSON.stringify(content)};\n`);
